stages:
    - test
    - build

test_job:
    image: golang:alpine3.13
    stage: test
    script:
        - go test
    
build_job:
    services:
        - docker:dind
    image: docker
    stage: build
    before_script:
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    script:      
        - docker build -t $CI_REGISTRY/vitaly.vasiliev/english-island-bot:latest .
        - docker push $CI_REGISTRY/vitaly.vasiliev/english-island-bot:latest
