stages:
    - build

build_job:
    services:
        - docker:dind
    image: docker
    stage: build
    before_script:
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    script:      
        - docker build .
        - docker push $CI_REGISTRY/vitaly.vasiliev/english-island-bot:latest
